### PR TITLE
Music Bank decompilation support.

### PR DESCRIPTION
**Pull request by Log0-git**
Support for music bank MFA writing... Also changed ID of music bank chunk. (taken from SourceExpolorer)

Duplicate of old pull req.: Audio formats support. Dumps audio files with correct file extensions.

### CODE REVIEW

**Review by AITYunivers — CHANGES_REQUESTED** [review]
`case 26217: // old 21217 (invalid)`
Please never remove chunk IDs we use. If you want to add a new chunk ID, make sure you have BOTH the old and the new, do:
`case 26217:`
`case 21217:`
    `code;`
    `break;`
Also add the chunk id to the `ChunkList.cs` file.

**Comment by Log0-git** [comment]
No need to add 26217 in the ChunkList.cs because it already has 26217. 

`ChunkList.cs Line 92             { 26217, "Music" },`

**Comment by AITYunivers** [comment]
Alright, just checking

**Comment by AITYunivers** [comment]
Okay apparently 21217 was a typo? I didn't know this, don't blame me, go ahead and revert the last commit.

**Comment by Log0-git** [comment]
ok

**Pull request merged**
